package com.mitarifamitaxi.taximetrousuario.resources

import com.mitarifamitaxi.taximetrousuario.models.Country

val countries = listOf(
    Country(name = "Afghanistan", dial = "+93", code = "AF"),
    Country(name = "Aland Islands", dial = "+358", code = "AX"),
    Country(name = "Albania", dial = "+355", code = "AL"),
    Country(name = "Algeria", dial = "+213", code = "DZ"),
    Country(name = "AmericanSamoa", dial = "+1684", code = "AS"),
    Country(name = "Andorra", dial = "+376", code = "AD"),
    Country(name = "Angola", dial = "+244", code = "AO"),
    Country(name = "Anguilla", dial = "+1264", code = "AI"),
    Country(name = "Antarctica", dial = "+672", code = "AQ"),
    Country(name = "Antigua and Barbuda", dial = "+1268", code = "AG"),
    Country(name = "Argentina", dial = "+54", code = "AR"),
    Country(name = "Armenia", dial = "+374", code = "AM"),
    Country(name = "Aruba", dial = "+297", code = "AW"),
    Country(name = "Australia", dial = "+61", code = "AU"),
    Country(name = "Austria", dial = "+43", code = "AT"),
    Country(name = "Azerbaijan", dial = "+994", code = "AZ"),
    Country(name = "Bahamas", dial = "+1242", code = "BS"),
    Country(name = "Bahrain", dial = "+973", code = "BH"),
    Country(name = "Bangladesh", dial = "+880", code = "BD"),
    Country(name = "Barbados", dial = "+1246", code = "BB"),
    Country(name = "Belarus", dial = "+375", code = "BY"),
    Country(name = "Belgium", dial = "+32", code = "BE"),
    Country(name = "Belize", dial = "+501", code = "BZ"),
    Country(name = "Benin", dial = "+229", code = "BJ"),
    Country(name = "Bermuda", dial = "+1441", code = "BM"),
    Country(name = "Bhutan", dial = "+975", code = "BT"),
    Country(name = "Bolivia, Plurinational State of", dial = "+591", code = "BO"),
    Country(name = "Bosnia and Herzegovina", dial = "+387", code = "BA"),
    Country(name = "Botswana", dial = "+267", code = "BW"),
    Country(name = "Brazil", dial = "+55", code = "BR"),
    Country(name = "British Indian Ocean Territory", dial = "+246", code = "IO"),
    Country(name = "Brunei Darussalam", dial = "+673", code = "BN"),
    Country(name = "Bulgaria", dial = "+359", code = "BG"),
    Country(name = "Burkina Faso", dial = "+226", code = "BF"),
    Country(name = "Burundi", dial = "+257", code = "BI"),
    Country(name = "Cambodia", dial = "+855", code = "KH"),
    Country(name = "Cameroon", dial = "+237", code = "CM"),
    Country(name = "Canada", dial = "+1", code = "CA"),
    Country(name = "Cape Verde", dial = "+238", code = "CV"),
    Country(name = "Cayman Islands", dial = "+ 345", code = "KY"),
    Country(name = "Central African Republic", dial = "+236", code = "CF"),
    Country(name = "Chad", dial = "+235", code = "TD"),
    Country(name = "Chile", dial = "+56", code = "CL"),
    Country(name = "China", dial = "+86", code = "CN"),
    Country(name = "Christmas Island", dial = "+61", code = "CX"),
    Country(name = "Cocos (Keeling) Islands", dial = "+61", code = "CC"),
    Country(name = "Colombia", dial = "+57", code = "CO"),
    Country(name = "Comoros", dial = "+269", code = "KM"),
    Country(name = "Congo", dial = "+242", code = "CG"),
    Country(name = "Congo, The Democratic Republic of the Congo", dial = "+243", code = "CD"),
    Country(name = "Cook Islands", dial = "+682", code = "CK"),
    Country(name = "Costa Rica", dial = "+506", code = "CR"),
    Country(name = "Cote d'Ivoire", dial = "+225", code = "CI"),
    Country(name = "Croatia", dial = "+385", code = "HR"),
    Country(name = "Cuba", dial = "+53", code = "CU"),
    Country(name = "Cyprus", dial = "+357", code = "CY"),
    Country(name = "Czech Republic", dial = "+420", code = "CZ"),
    Country(name = "Denmark", dial = "+45", code = "DK"),
    Country(name = "Djibouti", dial = "+253", code = "DJ"),
    Country(name = "Dominica", dial = "+1767", code = "DM"),
    Country(name = "Dominican Republic", dial = "+1849", code = "DO"),
    Country(name = "Ecuador", dial = "+593", code = "EC"),
    Country(name = "Egypt", dial = "+20", code = "EG"),
    Country(name = "El Salvador", dial = "+503", code = "SV"),
    Country(name = "Equatorial Guinea", dial = "+240", code = "GQ"),
    Country(name = "Eritrea", dial = "+291", code = "ER"),
    Country(name = "Estonia", dial = "+372", code = "EE"),
    Country(name = "Ethiopia", dial = "+251", code = "ET"),
    Country(name = "Falkland Islands (Malvinas)", dial = "+500", code = "FK"),
    Country(name = "Faroe Islands", dial = "+298", code = "FO"),
    Country(name = "Fiji", dial = "+679", code = "FJ"),
    Country(name = "Finland", dial = "+358", code = "FI"),
    Country(name = "France", dial = "+33", code = "FR"),
    Country(name = "French Guiana", dial = "+594", code = "GF"),
    Country(name = "French Polynesia", dial = "+689", code = "PF"),
    Country(name = "Gabon", dial = "+241", code = "GA"),
    Country(name = "Gambia", dial = "+220", code = "GM"),
    Country(name = "Georgia", dial = "+995", code = "GE"),
    Country(name = "Germany", dial = "+49", code = "DE"),
    Country(name = "Ghana", dial = "+233", code = "GH"),
    Country(name = "Gibraltar", dial = "+350", code = "GI"),
    Country(name = "Greece", dial = "+30", code = "GR"),
    Country(name = "Greenland", dial = "+299", code = "GL"),
    Country(name = "Grenada", dial = "+1473", code = "GD"),
    Country(name = "Guadeloupe", dial = "+590", code = "GP"),
    Country(name = "Guam", dial = "+1671", code = "GU"),
    Country(name = "Guatemala", dial = "+502", code = "GT"),
    Country(name = "Guernsey", dial = "+44", code = "GG"),
    Country(name = "Guinea", dial = "+224", code = "GN"),
    Country(name = "Guinea-Bissau", dial = "+245", code = "GW"),
    Country(name = "Guyana", dial = "+595", code = "GY"),
    Country(name = "Haiti", dial = "+509", code = "HT"),
    Country(name = "Holy See (Vatican City State)", dial = "+379", code = "VA"),
    Country(name = "Honduras", dial = "+504", code = "HN"),
    Country(name = "Hong Kong", dial = "+852", code = "HK"),
    Country(name = "Hungary", dial = "+36", code = "HU"),
    Country(name = "Iceland", dial = "+354", code = "IS"),
    Country(name = "India", dial = "+91", code = "IN"),
    Country(name = "Indonesia", dial = "+62", code = "ID"),
    Country(name = "Iran, Islamic Republic of Persian Gulf", dial = "+98", code = "IR"),
    Country(name = "Iraq", dial = "+964", code = "IQ"),
    Country(name = "Ireland", dial = "+353", code = "IE"),
    Country(name = "Isle of Man", dial = "+44", code = "IM"),
    Country(name = "Israel", dial = "+972", code = "IL"),
    Country(name = "Italy", dial = "+39", code = "IT"),
    Country(name = "Jamaica", dial = "+1876", code = "JM"),
    Country(name = "Japan", dial = "+81", code = "JP"),
    Country(name = "Jersey", dial = "+44", code = "JE"),
    Country(name = "Jordan", dial = "+962", code = "JO"),
    Country(name = "Kazakhstan", dial = "+77", code = "KZ"),
    Country(name = "Kenya", dial = "+254", code = "KE"),
    Country(name = "Kiribati", dial = "+686", code = "KI"),
    Country(name = "Korea, Democratic People's Republic of Korea", dial = "+850", code = "KP"),
    Country(name = "Korea, Republic of South Korea", dial = "+82", code = "KR"),
    Country(name = "Kuwait", dial = "+965", code = "KW"),
    Country(name = "Kyrgyzstan", dial = "+996", code = "KG"),
    Country(name = "Laos", dial = "+856", code = "LA"),
    Country(name = "Latvia", dial = "+371", code = "LV"),
    Country(name = "Lebanon", dial = "+961", code = "LB"),
    Country(name = "Lesotho", dial = "+266", code = "LS"),
    Country(name = "Liberia", dial = "+231", code = "LR"),
    Country(name = "Libyan Arab Jamahiriya", dial = "+218", code = "LY"),
    Country(name = "Liechtenstein", dial = "+423", code = "LI"),
    Country(name = "Lithuania", dial = "+370", code = "LT"),
    Country(name = "Luxembourg", dial = "+352", code = "LU"),
    Country(name = "Macao", dial = "+853", code = "MO"),
    Country(name = "Macedonia", dial = "+389", code = "MK"),
    Country(name = "Madagascar", dial = "+261", code = "MG"),
    Country(name = "Malawi", dial = "+265", code = "MW"),
    Country(name = "Malaysia", dial = "+60", code = "MY"),
    Country(name = "Maldives", dial = "+960", code = "MV"),
    Country(name = "Mali", dial = "+223", code = "ML"),
    Country(name = "Malta", dial = "+356", code = "MT"),
    Country(name = "Marshall Islands", dial = "+692", code = "MH"),
    Country(name = "Martinique", dial = "+596", code = "MQ"),
    Country(name = "Mauritania", dial = "+222", code = "MR"),
    Country(name = "Mauritius", dial = "+230", code = "MU"),
    Country(name = "Mayotte", dial = "+262", code = "YT"),
    Country(name = "Mexico", dial = "+52", code = "MX"),
    Country(name = "Micronesia, Federated States of Micronesia", dial = "+691", code = "FM"),
    Country(name = "Moldova", dial = "+373", code = "MD"),
    Country(name = "Monaco", dial = "+377", code = "MC"),
    Country(name = "Mongolia", dial = "+976", code = "MN"),
    Country(name = "Montenegro", dial = "+382", code = "ME"),
    Country(name = "Montserrat", dial = "+1664", code = "MS"),
    Country(name = "Morocco", dial = "+212", code = "MA"),
    Country(name = "Mozambique", dial = "+258", code = "MZ"),
    Country(name = "Myanmar", dial = "+95", code = "MM"),
    Country(name = "Namibia", dial = "+264", code = "NA"),
    Country(name = "Nauru", dial = "+674", code = "NR"),
    Country(name = "Nepal", dial = "+977", code = "NP"),
    Country(name = "Netherlands", dial = "+31", code = "NL"),
    Country(name = "Netherlands Antilles", dial = "+599", code = "AN"),
    Country(name = "New Caledonia", dial = "+687", code = "NC"),
    Country(name = "New Zealand", dial = "+64", code = "NZ"),
    Country(name = "Nicaragua", dial = "+505", code = "NI"),
    Country(name = "Niger", dial = "+227", code = "NE"),
    Country(name = "Nigeria", dial = "+234", code = "NG"),
    Country(name = "Niue", dial = "+683", code = "NU"),
    Country(name = "Norfolk Island", dial = "+672", code = "NF"),
    Country(name = "Northern Mariana Islands", dial = "+1670", code = "MP"),
    Country(name = "Norway", dial = "+47", code = "NO"),
    Country(name = "Oman", dial = "+968", code = "OM"),
    Country(name = "Pakistan", dial = "+92", code = "PK"),
    Country(name = "Palau", dial = "+680", code = "PW"),
    Country(name = "Palestinian Territory, Occupied", dial = "+970", code = "PS"),
    Country(name = "Panama", dial = "+507", code = "PA"),
    Country(name = "Papua New Guinea", dial = "+675", code = "PG"),
    Country(name = "Paraguay", dial = "+595", code = "PY"),
    Country(name = "Peru", dial = "+51", code = "PE"),
    Country(name = "Philippines", dial = "+63", code = "PH"),
    Country(name = "Pitcairn", dial = "+872", code = "PN"),
    Country(name = "Poland", dial = "+48", code = "PL"),
    Country(name = "Portugal", dial = "+351", code = "PT"),
    Country(name = "Puerto Rico", dial = "+1939", code = "PR"),
    Country(name = "Qatar", dial = "+974", code = "QA"),
    Country(name = "Romania", dial = "+40", code = "RO"),
    Country(name = "Russia", dial = "+7", code = "RU"),
    Country(name = "Rwanda", dial = "+250", code = "RW"),
    Country(name = "Reunion", dial = "+262", code = "RE"),
    Country(name = "Saint Barthelemy", dial = "+590", code = "BL"),
    Country(name = "Saint Helena, Ascension and Tristan Da Cunha", dial = "+290", code = "SH"),
    Country(name = "Saint Kitts and Nevis", dial = "+1869", code = "KN"),
    Country(name = "Saint Lucia", dial = "+1758", code = "LC"),
    Country(name = "Saint Martin", dial = "+590", code = "MF"),
    Country(name = "Saint Pierre and Miquelon", dial = "+508", code = "PM"),
    Country(name = "Saint Vincent and the Grenadines", dial = "+1784", code = "VC"),
    Country(name = "Samoa", dial = "+685", code = "WS"),
    Country(name = "San Marino", dial = "+378", code = "SM"),
    Country(name = "Sao Tome and Principe", dial = "+239", code = "ST"),
    Country(name = "Saudi Arabia", dial = "+966", code = "SA"),
    Country(name = "Senegal", dial = "+221", code = "SN"),
    Country(name = "Serbia", dial = "+381", code = "RS"),
    Country(name = "Seychelles", dial = "+248", code = "SC"),
    Country(name = "Sierra Leone", dial = "+232", code = "SL"),
    Country(name = "Singapore", dial = "+65", code = "SG"),
    Country(name = "Slovakia", dial = "+421", code = "SK"),
    Country(name = "Slovenia", dial = "+386", code = "SI"),
    Country(name = "Solomon Islands", dial = "+677", code = "SB"),
    Country(name = "Somalia", dial = "+252", code = "SO"),
    Country(name = "South Africa", dial = "+27", code = "ZA"),
    Country(name = "South Sudan", dial = "+211", code = "SS"),
    Country(name = "South Georgia and the South Sandwich Islands", dial = "+500", code = "GS"),
    Country(name = "Spain", dial = "+34", code = "ES"),
    Country(name = "Sri Lanka", dial = "+94", code = "LK"),
    Country(name = "Sudan", dial = "+249", code = "SD"),
    Country(name = "Suriname", dial = "+597", code = "SR"),
    Country(name = "Svalbard and Jan Mayen", dial = "+47", code = "SJ"),
    Country(name = "Swaziland", dial = "+268", code = "SZ"),
    Country(name = "Sweden", dial = "+46", code = "SE"),
    Country(name = "Switzerland", dial = "+41", code = "CH"),
    Country(name = "Syrian Arab Republic", dial = "+963", code = "SY"),
    Country(name = "Taiwan", dial = "+886", code = "TW"),
    Country(name = "Tajikistan", dial = "+992", code = "TJ"),
    Country(name = "Tanzania, United Republic of Tanzania", dial = "+255", code = "TZ"),
    Country(name = "Thailand", dial = "+66", code = "TH"),
    Country(name = "Timor-Leste", dial = "+670", code = "TL"),
    Country(name = "Togo", dial = "+228", code = "TG"),
    Country(name = "Tokelau", dial = "+690", code = "TK"),
    Country(name = "Tonga", dial = "+676", code = "TO"),
    Country(name = "Trinidad and Tobago", dial = "+1868", code = "TT"),
    Country(name = "Tunisia", dial = "+216", code = "TN"),
    Country(name = "Turkey", dial = "+90", code = "TR"),
    Country(name = "Turkmenistan", dial = "+993", code = "TM"),
    Country(name = "Turks and Caicos Islands", dial = "+1649", code = "TC"),
    Country(name = "Tuvalu", dial = "+688", code = "TV"),
    Country(name = "Uganda", dial = "+256", code = "UG"),
    Country(name = "Ukraine", dial = "+380", code = "UA"),
    Country(name = "United Arab Emirates", dial = "+971", code = "AE"),
    Country(name = "United Kingdom", dial = "+44", code = "GB"),
    Country(name = "United States", dial = "+1", code = "US"),
    Country(name = "Uruguay", dial = "+598", code = "UY"),
    Country(name = "Uzbekistan", dial = "+998", code = "UZ"),
    Country(name = "Vanuatu", dial = "+678", code = "VU"),
    Country(name = "Venezuela, Bolivarian Republic of Venezuela", dial = "+58", code = "VE"),
    Country(name = "Vietnam", dial = "+84", code = "VN"),
    Country(name = "Virgin Islands, British", dial = "+1284", code = "VG"),
    Country(name = "Virgin Islands, U.S.", dial = "+1340", code = "VI"),
    Country(name = "Wallis and Futuna", dial = "+681", code = "WF"),
    Country(name = "Yemen", dial = "+967", code = "YE"),
    Country(name = "Zambia", dial = "+260", code = "ZM"),
    Country(name = "Zimbabwe", dial = "+263", code = "ZW")
)
