package com.mitarifamitaxi.taximetrousuario.resources

import com.mitarifamitaxi.taximetrousuario.models.Country

val countries = listOf(
    Country(name = "Afghanistan", dial = "+93", code = "AF", currency = "AFN"),
    Country(name = "Aland Islands", dial = "+358", code = "AX", currency = "EUR"),
    Country(name = "Albania", dial = "+355", code = "AL", currency = "ALL"),
    Country(name = "Algeria", dial = "+213", code = "DZ", currency = "DZD"),
    Country(name = "AmericanSamoa", dial = "+1684", code = "AS", currency = "USD"),
    Country(name = "Andorra", dial = "+376", code = "AD", currency = "EUR"),
    Country(name = "Angola", dial = "+244", code = "AO", currency = "AOA"),
    Country(name = "Anguilla", dial = "+1264", code = "AI", currency = "XCD"),
    Country(name = "Antarctica", dial = "+672", code = "AQ", currency = "NOK"),
    Country(name = "Antigua and Barbuda", dial = "+1268", code = "AG", currency = "XCD"),
    Country(name = "Argentina", dial = "+54", code = "AR", currency = "ARS"),
    Country(name = "Armenia", dial = "+374", code = "AM", currency = "AMD"),
    Country(name = "Aruba", dial = "+297", code = "AW", currency = "AWG"),
    Country(name = "Australia", dial = "+61", code = "AU", currency = "AUD"),
    Country(name = "Austria", dial = "+43", code = "AT", currency = "EUR"),
    Country(name = "Azerbaijan", dial = "+994", code = "AZ", currency = "AZN"),
    Country(name = "Bahamas", dial = "+1242", code = "BS", currency = "BSD"),
    Country(name = "Bahrain", dial = "+973", code = "BH", currency = "BHD"),
    Country(name = "Bangladesh", dial = "+880", code = "BD", currency = "BDT"),
    Country(name = "Barbados", dial = "+1246", code = "BB", currency = "BBD"),
    Country(name = "Belarus", dial = "+375", code = "BY", currency = "BYN"),
    Country(name = "Belgium", dial = "+32", code = "BE", currency = "EUR"),
    Country(name = "Belize", dial = "+501", code = "BZ", currency = "BZD"),
    Country(name = "Benin", dial = "+229", code = "BJ", currency = "XOF"),
    Country(name = "Bermuda", dial = "+1441", code = "BM", currency = "BMD"),
    Country(name = "Bhutan", dial = "+975", code = "BT", currency = "BTN"),
    Country(name = "Bolivia, Plurinational State of", dial = "+591", code = "BO", currency = "BOB"),
    Country(name = "Bosnia and Herzegovina", dial = "+387", code = "BA", currency = "BAM"),
    Country(name = "Botswana", dial = "+267", code = "BW", currency = "BWP"),
    Country(name = "Brazil", dial = "+55", code = "BR", currency = "BRL"),
    Country(name = "British Indian Ocean Territory", dial = "+246", code = "IO", currency = "USD"),
    Country(name = "Brunei Darussalam", dial = "+673", code = "BN", currency = "BND"),
    Country(name = "Bulgaria", dial = "+359", code = "BG", currency = "BGN"),
    Country(name = "Burkina Faso", dial = "+226", code = "BF", currency = "XOF"),
    Country(name = "Burundi", dial = "+257", code = "BI", currency = "BIF"),
    Country(name = "Cambodia", dial = "+855", code = "KH", currency = "KHR"),
    Country(name = "Cameroon", dial = "+237", code = "CM", currency = "XAF"),
    Country(name = "Canada", dial = "+1", code = "CA", currency = "CAD"),
    Country(name = "Cape Verde", dial = "+238", code = "CV", currency = "CVE"),
    Country(name = "Cayman Islands", dial = "+ 345", code = "KY", currency = "KYD"),
    Country(name = "Central African Republic", dial = "+236", code = "CF", currency = "XAF"),
    Country(name = "Chad", dial = "+235", code = "TD", currency = "XAF"),
    Country(name = "Chile", dial = "+56", code = "CL", currency = "CLP"),
    Country(name = "China", dial = "+86", code = "CN", currency = "CNY"),
    Country(name = "Christmas Island", dial = "+61", code = "CX", currency = "AUD"),
    Country(name = "Cocos (Keeling) Islands", dial = "+61", code = "CC", currency = "AUD"),
    Country(name = "Colombia", dial = "+57", code = "CO", currency = "COP"),
    Country(name = "Comoros", dial = "+269", code = "KM", currency = "KMF"),
    Country(name = "Congo", dial = "+242", code = "CG", currency = "XAF"),
    Country(name = "Congo, The Democratic Republic of the Congo", dial = "+243", code = "CD", currency = "CDF"),
    Country(name = "Cook Islands", dial = "+682", code = "CK", currency = "NZD"),
    Country(name = "Costa Rica", dial = "+506", code = "CR", currency = "CRC"),
    Country(name = "Cote d'Ivoire", dial = "+225", code = "CI", currency = "XOF"),
    Country(name = "Croatia", dial = "+385", code = "HR", currency = "EUR"),
    Country(name = "Cuba", dial = "+53", code = "CU", currency = "CUP"),
    Country(name = "Cyprus", dial = "+357", code = "CY", currency = "EUR"),
    Country(name = "Czech Republic", dial = "+420", code = "CZ", currency = "CZK"),
    Country(name = "Denmark", dial = "+45", code = "DK", currency = "DKK"),
    Country(name = "Djibouti", dial = "+253", code = "DJ", currency = "DJF"),
    Country(name = "Dominica", dial = "+1767", code = "DM", currency = "XCD"),
    Country(name = "Dominican Republic", dial = "+1849", code = "DO", currency = "DOP"),
    Country(name = "Ecuador", dial = "+593", code = "EC", currency = "USD"),
    Country(name = "Egypt", dial = "+20", code = "EG", currency = "EGP"),
    Country(name = "El Salvador", dial = "+503", code = "SV", currency = "USD"),
    Country(name = "Equatorial Guinea", dial = "+240", code = "GQ", currency = "XAF"),
    Country(name = "Eritrea", dial = "+291", code = "ER", currency = "ERN"),
    Country(name = "Estonia", dial = "+372", code = "EE", currency = "EUR"),
    Country(name = "Ethiopia", dial = "+251", code = "ET", currency = "ETB"),
    Country(name = "Falkland Islands (Malvinas)", dial = "+500", code = "FK", currency = "FKP"),
    Country(name = "Faroe Islands", dial = "+298", code = "FO", currency = "DKK"),
    Country(name = "Fiji", dial = "+679", code = "FJ", currency = "FJD"),
    Country(name = "Finland", dial = "+358", code = "FI", currency = "EUR"),
    Country(name = "France", dial = "+33", code = "FR", currency = "EUR"),
    Country(name = "French Guiana", dial = "+594", code = "GF", currency = "EUR"),
    Country(name = "French Polynesia", dial = "+689", code = "PF", currency = "XPF"),
    Country(name = "Gabon", dial = "+241", code = "GA", currency = "XAF"),
    Country(name = "Gambia", dial = "+220", code = "GM", currency = "GMD"),
    Country(name = "Georgia", dial = "+995", code = "GE", currency = "GEL"),
    Country(name = "Germany", dial = "+49", code = "DE", currency = "EUR"),
    Country(name = "Ghana", dial = "+233", code = "GH", currency = "GHS"),
    Country(name = "Gibraltar", dial = "+350", code = "GI", currency = "GIP"),
    Country(name = "Greece", dial = "+30", code = "GR", currency = "EUR"),
    Country(name = "Greenland", dial = "+299", code = "GL", currency = "DKK"),
    Country(name = "Grenada", dial = "+1473", code = "GD", currency = "XCD"),
    Country(name = "Guadeloupe", dial = "+590", code = "GP", currency = "EUR"),
    Country(name = "Guam", dial = "+1671", code = "GU", currency = "USD"),
    Country(name = "Guatemala", dial = "+502", code = "GT", currency = "GTQ"),
    Country(name = "Guernsey", dial = "+44", code = "GG", currency = "GBP"),
    Country(name = "Guinea", dial = "+224", code = "GN", currency = "GNF"),
    Country(name = "Guinea-Bissau", dial = "+245", code = "GW", currency = "XOF"),
    Country(name = "Guyana", dial = "+595", code = "GY", currency = "GYD"),
    Country(name = "Haiti", dial = "+509", code = "HT", currency = "HTG"),
    Country(name = "Holy See (Vatican City State)", dial = "+379", code = "VA", currency = "EUR"),
    Country(name = "Honduras", dial = "+504", code = "HN", currency = "HNL"),
    Country(name = "Hong Kong", dial = "+852", code = "HK", currency = "HKD"),
    Country(name = "Hungary", dial = "+36", code = "HU", currency = "HUF"),
    Country(name = "Iceland", dial = "+354", code = "IS", currency = "ISK"),
    Country(name = "India", dial = "+91", code = "IN", currency = "INR"),
    Country(name = "Indonesia", dial = "+62", code = "ID", currency = "IDR"),
    Country(name = "Iran, Islamic Republic of Persian Gulf", dial = "+98", code = "IR", currency = "IRR"),
    Country(name = "Iraq", dial = "+964", code = "IQ", currency = "IQD"),
    Country(name = "Ireland", dial = "+353", code = "IE", currency = "EUR"),
    Country(name = "Isle of Man", dial = "+44", code = "IM", currency = "GBP"),
    Country(name = "Israel", dial = "+972", code = "IL", currency = "ILS"),
    Country(name = "Italy", dial = "+39", code = "IT", currency = "EUR"),
    Country(name = "Jamaica", dial = "+1876", code = "JM", currency = "JMD"),
    Country(name = "Japan", dial = "+81", code = "JP", currency = "JPY"),
    Country(name = "Jersey", dial = "+44", code = "JE", currency = "GBP"),
    Country(name = "Jordan", dial = "+962", code = "JO", currency = "JOD"),
    Country(name = "Kazakhstan", dial = "+77", code = "KZ", currency = "KZT"),
    Country(name = "Kenya", dial = "+254", code = "KE", currency = "KES"),
    Country(name = "Kiribati", dial = "+686", code = "KI", currency = "AUD"),
    Country(name = "Korea, Democratic People's Republic of Korea", dial = "+850", code = "KP", currency = "KPW"),
    Country(name = "Korea, Republic of South Korea", dial = "+82", code = "KR", currency = "KRW"),
    Country(name = "Kuwait", dial = "+965", code = "KW", currency = "KWD"),
    Country(name = "Kyrgyzstan", dial = "+996", code = "KG", currency = "KGS"),
    Country(name = "Laos", dial = "+856", code = "LA", currency = "LAK"),
    Country(name = "Latvia", dial = "+371", code = "LV", currency = "EUR"),
    Country(name = "Lebanon", dial = "+961", code = "LB", currency = "LBP"),
    Country(name = "Lesotho", dial = "+266", code = "LS", currency = "LSL"),
    Country(name = "Liberia", dial = "+231", code = "LR", currency = "LRD"),
    Country(name = "Libyan Arab Jamahiriya", dial = "+218", code = "LY", currency = "LYD"),
    Country(name = "Liechtenstein", dial = "+423", code = "LI", currency = "CHF"),
    Country(name = "Lithuania", dial = "+370", code = "LT", currency = "EUR"),
    Country(name = "Luxembourg", dial = "+352", code = "LU", currency = "EUR"),
    Country(name = "Macao", dial = "+853", code = "MO", currency = "MOP"),
    Country(name = "Macedonia", dial = "+389", code = "MK", currency = "MKD"),
    Country(name = "Madagascar", dial = "+261", code = "MG", currency = "MGA"),
    Country(name = "Malawi", dial = "+265", code = "MW", currency = "MWK"),
    Country(name = "Malaysia", dial = "+60", code = "MY", currency = "MYR"),
    Country(name = "Maldives", dial = "+960", code = "MV", currency = "MVR"),
    Country(name = "Mali", dial = "+223", code = "ML", currency = "XOF"),
    Country(name = "Malta", dial = "+356", code = "MT", currency = "EUR"),
    Country(name = "Marshall Islands", dial = "+692", code = "MH", currency = "USD"),
    Country(name = "Martinique", dial = "+596", code = "MQ", currency = "EUR"),
    Country(name = "Mauritania", dial = "+222", code = "MR", currency = "MRU"),
    Country(name = "Mauritius", dial = "+230", code = "MU", currency = "MUR"),
    Country(name = "Mayotte", dial = "+262", code = "YT", currency = "EUR"),
    Country(name = "Mexico", dial = "+52", code = "MX", currency = "MXN"),
    Country(name = "Micronesia, Federated States of Micronesia", dial = "+691", code = "FM", currency = "USD"),
    Country(name = "Moldova", dial = "+373", code = "MD", currency = "MDL"),
    Country(name = "Monaco", dial = "+377", code = "MC", currency = "EUR"),
    Country(name = "Mongolia", dial = "+976", code = "MN", currency = "MNT"),
    Country(name = "Montenegro", dial = "+382", code = "ME", currency = "EUR"),
    Country(name = "Montserrat", dial = "+1664", code = "MS", currency = "XCD"),
    Country(name = "Morocco", dial = "+212", code = "MA", currency = "MAD"),
    Country(name = "Mozambique", dial = "+258", code = "MZ", currency = "MZN"),
    Country(name = "Myanmar", dial = "+95", code = "MM", currency = "MMK"),
    Country(name = "Namibia", dial = "+264", code = "NA", currency = "NAD"),
    Country(name = "Nauru", dial = "+674", code = "NR", currency = "AUD"),
    Country(name = "Nepal", dial = "+977", code = "NP", currency = "NPR"),
    Country(name = "Netherlands", dial = "+31", code = "NL", currency = "EUR"),
    Country(name = "Netherlands Antilles", dial = "+599", code = "AN", currency = "ANG"),
    Country(name = "New Caledonia", dial = "+687", code = "NC", currency = "XPF"),
    Country(name = "New Zealand", dial = "+64", code = "NZ", currency = "NZD"),
    Country(name = "Nicaragua", dial = "+505", code = "NI", currency = "NIO"),
    Country(name = "Niger", dial = "+227", code = "NE", currency = "XOF"),
    Country(name = "Nigeria", dial = "+234", code = "NG", currency = "NGN"),
    Country(name = "Niue", dial = "+683", code = "NU", currency = "NZD"),
    Country(name = "Norfolk Island", dial = "+672", code = "NF", currency = "AUD"),
    Country(name = "Northern Mariana Islands", dial = "+1670", code = "MP", currency = "USD"),
    Country(name = "Norway", dial = "+47", code = "NO", currency = "NOK"),
    Country(name = "Oman", dial = "+968", code = "OM", currency = "OMR"),
    Country(name = "Pakistan", dial = "+92", code = "PK", currency = "PKR"),
    Country(name = "Palau", dial = "+680", code = "PW", currency = "USD"),
    Country(name = "Palestinian Territory, Occupied", dial = "+970", code = "PS", currency = "ILS"),
    Country(name = "Panama", dial = "+507", code = "PA", currency = "PAB"),
    Country(name = "Papua New Guinea", dial = "+675", code = "PG", currency = "PGK"),
    Country(name = "Paraguay", dial = "+595", code = "PY", currency = "PYG"),
    Country(name = "Peru", dial = "+51", code = "PE", currency = "PEN"),
    Country(name = "Philippines", dial = "+63", code = "PH", currency = "PHP"),
    Country(name = "Pitcairn", dial = "+872", code = "PN", currency = "NZD"),
    Country(name = "Poland", dial = "+48", code = "PL", currency = "PLN"),
    Country(name = "Portugal", dial = "+351", code = "PT", currency = "EUR"),
    Country(name = "Puerto Rico", dial = "+1939", code = "PR", currency = "USD"),
    Country(name = "Qatar", dial = "+974", code = "QA", currency = "QAR"),
    Country(name = "Romania", dial = "+40", code = "RO", currency = "RON"),
    Country(name = "Russia", dial = "+7", code = "RU", currency = "RUB"),
    Country(name = "Rwanda", dial = "+250", code = "RW", currency = "RWF"),
    Country(name = "Reunion", dial = "+262", code = "RE", currency = "EUR"),
    Country(name = "Saint Barthelemy", dial = "+590", code = "BL", currency = "EUR"),
    Country(name = "Saint Helena, Ascension and Tristan Da Cunha", dial = "+290", code = "SH", currency = "SHP"),
    Country(name = "Saint Kitts and Nevis", dial = "+1869", code = "KN", currency = "XCD"),
    Country(name = "Saint Lucia", dial = "+1758", code = "LC", currency = "XCD"),
    Country(name = "Saint Martin", dial = "+590", code = "MF", currency = "EUR"),
    Country(name = "Saint Pierre and Miquelon", dial = "+508", code = "PM", currency = "EUR"),
    Country(name = "Saint Vincent and the Grenadines", dial = "+1784", code = "VC", currency = "XCD"),
    Country(name = "Samoa", dial = "+685", code = "WS", currency = "WST"),
    Country(name = "San Marino", dial = "+378", code = "SM", currency = "EUR"),
    Country(name = "Sao Tome and Principe", dial = "+239", code = "ST", currency = "STD"),
    Country(name = "Saudi Arabia", dial = "+966", code = "SA", currency = "SAR"),
    Country(name = "Senegal", dial = "+221", code = "SN", currency = "XOF"),
    Country(name = "Serbia", dial = "+381", code = "RS", currency = "RSD"),
    Country(name = "Seychelles", dial = "+248", code = "SC", currency = "SCR"),
    Country(name = "Sierra Leone", dial = "+232", code = "SL", currency = "SLL"),
    Country(name = "Singapore", dial = "+65", code = "SG", currency = "SGD"),
    Country(name = "Slovakia", dial = "+421", code = "SK", currency = "EUR"),
    Country(name = "Slovenia", dial = "+386", code = "SI", currency = "EUR"),
    Country(name = "Solomon Islands", dial = "+677", code = "SB", currency = "SBD"),
    Country(name = "Somalia", dial = "+252", code = "SO", currency = "SOS"),
    Country(name = "South Africa", dial = "+27", code = "ZA", currency = "ZAR"),
    Country(name = "South Sudan", dial = "+211", code = "SS", currency = "SSP"),
    Country(name = "South Georgia and the South Sandwich Islands", dial = "+500", code = "GS", currency = "GBP"),
    Country(name = "Spain", dial = "+34", code = "ES", currency = "EUR"),
    Country(name = "Sri Lanka", dial = "+94", code = "LK", currency = "LKR"),
    Country(name = "Sudan", dial = "+249", code = "SD", currency = "SDG"),
    Country(name = "Suriname", dial = "+597", code = "SR", currency = "SRD"),
    Country(name = "Svalbard and Jan Mayen", dial = "+47", code = "SJ", currency = "NOK"),
    Country(name = "Swaziland", dial = "+268", code = "SZ", currency = "SZL"),
    Country(name = "Sweden", dial = "+46", code = "SE", currency = "SEK"),
    Country(name = "Switzerland", dial = "+41", code = "CH", currency = "CHF"),
    Country(name = "Syrian Arab Republic", dial = "+963", code = "SY", currency = "SYP"),
    Country(name = "Taiwan", dial = "+886", code = "TW", currency = "TWD"),
    Country(name = "Tajikistan", dial = "+992", code = "TJ", currency = "TJS"),
    Country(name = "Tanzania, United Republic of Tanzania", dial = "+255", code = "TZ", currency = "TZS"),
    Country(name = "Thailand", dial = "+66", code = "TH", currency = "THB"),
    Country(name = "Timor-Leste", dial = "+670", code = "TL", currency = "USD"),
    Country(name = "Togo", dial = "+228", code = "TG", currency = "XOF"),
    Country(name = "Tokelau", dial = "+690", code = "TK", currency = "NZD"),
    Country(name = "Tonga", dial = "+676", code = "TO", currency = "TOP"),
    Country(name = "Trinidad and Tobago", dial = "+1868", code = "TT", currency = "TTD"),
    Country(name = "Tunisia", dial = "+216", code = "TN", currency = "TND"),
    Country(name = "Turkey", dial = "+90", code = "TR", currency = "TRY"),
    Country(name = "Turkmenistan", dial = "+993", code = "TM", currency = "TMT"),
    Country(name = "Turks and Caicos Islands", dial = "+1649", code = "TC", currency = "USD"),
    Country(name = "Tuvalu", dial = "+688", code = "TV", currency = "AUD"),
    Country(name = "Uganda", dial = "+256", code = "UG", currency = "UGX"),
    Country(name = "Ukraine", dial = "+380", code = "UA", currency = "UAH"),
    Country(name = "United Arab Emirates", dial = "+971", code = "AE", currency = "AED"),
    Country(name = "United Kingdom", dial = "+44", code = "GB", currency = "GBP"),
    Country(name = "United States", dial = "+1", code = "US", currency = "USD"),
    Country(name = "Uruguay", dial = "+598", code = "UY", currency = "UYU"),
    Country(name = "Uzbekistan", dial = "+998", code = "UZ", currency = "UZS"),
    Country(name = "Vanuatu", dial = "+678", code = "VU", currency = "VUV"),
    Country(name = "Venezuela, Bolivarian Republic of Venezuela", dial = "+58", code = "VE", currency = "VES"),
    Country(name = "Vietnam", dial = "+84", code = "VN", currency = "VND"),
    Country(name = "Virgin Islands, British", dial = "+1284", code = "VG", currency = "USD"),
    Country(name = "Virgin Islands, U.S.", dial = "+1340", code = "VI", currency = "USD"),
    Country(name = "Wallis and Futuna", dial = "+681", code = "WF", currency = "XPF"),
    Country(name = "Yemen", dial = "+967", code = "YE", currency = "YER"),
    Country(name = "Zambia", dial = "+260", code = "ZM", currency = "ZMW"),
    Country(name = "Zimbabwe", dial = "+263", code = "ZW", currency = "ZWL")
)